const product = [
    {
        id: 1,
        name: 'Fernet 750ML',
        stock: 20,
        price: 800,
        categoryId: 1,
        category: {
            name: 'destilados',
            id: 1,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649736460/Fondo/FERNET_BRANCA_750ml_tcmaab.jpg',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 2,
        name: 'Chandon 750ml',
        stock: 30,
        price: 1200,
        categoryId:2,
        category: {
            name: 'espumantes',
            id: 2,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649962455/Fondo/CHANDON_EXTRA_BRUT_750ml_hj7ue6.jpg',
        description:'La descripcion cjanclndjvnjvnsjvnsnvkzdnvknj <bmvbjbvjbfb<jcnakfbsjdncjk<bshjebkjbdjfv<jhbf',
    },
    {
        id: 3,
        name: 'Smirnoff 750ml',
        stock: 20,
        price: 700,
        categoryId: 1,
        category: {
            name: 'destilados',
            id: 1,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649962606/Fondo/2169_SMIRNOFF_750ml_yhiigy.jpg',
        description:'La descripcion cjanclndjvnjvnsjvnsnvkzdnvknj <bmvbjbvjbfb<jcnakfbsjdncjk<bshjebkjbdjfv<jhbf',
    },
    {id: 4,
        name: 'Baron B',
        stock: 33,
        price: 2200,
        categoryId: 2,
        category: {
            name: 'espumantes',
            id: 2,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649962894/Fondo/4597_BARON_B_EXTRA_BRUT_ROSE_750ml_y4yxh6.png',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {id: 5,
        name: 'Corona',
        stock: 44,
        price: 500,
        categoryId: 3,
        category: {
            name: 'cervezas',
            id: 3,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649962948/Fondo/873_CORONA_710ml_hpawrf.jpg',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {id: 6,
        name: 'Miller 710ml',
        stock: 65,
        price: 600,
        categoryId: 3,
        category: {
            name: 'cervezas',
            id: 3,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649962981/Fondo/1669_MILLER_330ml_d5bbeu.jpg',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {id: 7,
        name: 'Callia malbec',
        stock: 21,
        price: 450,
        categoryId: 4,
        category: {
            name: 'vinos',
            id: 4,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649963090/Fondo/4933_CALLIA_HOY_MALBEC_750ml_bbjs65.png',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {id: 8,
        name: 'Crios Chenni',
        stock: 54,
        price: 600,
        categoryId: 4,
        category: {
            name: 'vinos',
            id: 4,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649963112/Fondo/4494_CRIOS_CHENIN_750ml_n1uwte.png',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {id: 9,
        name: 'Johnnie Walker',
        stock: 43,
        price: 2400,
        categoryId: 1,
        category: {
            name: 'destilados',
            id: 1,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649963168/Fondo/1419_JOHNNIE_WALKER_RED_LABEL_1000ml_quccaq.jpg',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {id: 10,
        name: 'Navarro Correas',
        stock: 55,
        price: 1000,
        categoryId: 2,
        category: {
            name: 'espumantes',
            id: 2,
        },
        img: 'https://res.cloudinary.com/ddyfnbcts/image/upload/v1649963207/Fondo/2778_NAVARRO_CORREAS_NATURE_750ml_lw87eo.jpg',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
] 
module.exports= {
    product,
}